## Import libraries

In [1]:
import pandas as pd
import numpy as np
from urllib.request import urlopen
from zipfile import ZipFile
from io import BytesIO

## Zip file to dataframe

* CSV Flandres  - https://opendata.bosa.be/download/best/openaddress-bevlg.zip
* CSV Région de Bruxelles  - https://opendata.bosa.be/download/best/openaddress-bebru.zip
* CSV Wallonie - https://opendata.bosa.be/download/best/openaddress-bewal.zip

In [2]:
# download and open zip file from a website and then create a dataframe from csv file from the zip file 

def open_zip(url,csv):

    zip_in_memory = urlopen(url).read()

    z = ZipFile(BytesIO(zip_in_memory))
    
    df = pd.read_csv(z.open(csv))
    
    return df

In [3]:
# open zip CSV Flandres - https://opendata.bosa.be/download/best/openaddress-bevlg.zip

csv_file_fl = 'openaddress-bevlg.csv'
zip_fl = 'https://opendata.bosa.be/download/best/openaddress-bevlg.zip'
df_flandre = open_zip(zip_fl,csv_file_fl)

/Users/adamtky/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3263: DtypeWarning: Columns (5,8,9,12,16) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [4]:
# open zip CSV Région de Bruxelles - https://opendata.bosa.be/download/best/openaddress-bebru.zip

csv_file_bru = 'openaddress-bebru.csv'
zip_bru = 'https://opendata.bosa.be/download/best/openaddress-bebru.zip'
df_bru = open_zip(zip_bru,csv_file_bru)

/Users/adamtky/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3263: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [6]:
# open zip CSV Wallonie - https://opendata.bosa.be/download/best/openaddress-bewal.zip

csv_file_wal = 'openaddress-bewal.csv'
zip_wal = 'https://opendata.bosa.be/download/best/openaddress-bewal.zip'
df_wal = open_zip(zip_wal,csv_file_wal)

/Users/adamtky/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3263: DtypeWarning: Columns (5,8,15) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

## Flandre Addresses

In [8]:
df_flandre.head()

,EPSG:31370_x,EPSG:31370_y,EPSG:4326_lat,EPSG:4326_lon,address_id,box_number,house_number,municipality_id,municipality_name_de,municipality_name_fr,municipality_name_nl,postcode,postname_fr,postname_nl,street_id,streetname_de,streetname_fr,streetname_nl,region_code,status
0,190710.56,224659.47,51.330293,4.952837,205001,NaN,51,13040,NaN,NaN,Turnhout,2300,NaN,Turnhout,17718,NaN,NaN,Steenweg op Oosthoven,BE-VLG,current
1,158832.72,192858.98,51.045829,4.494707,205002,NaN,102,12025,Mechelen,Malines,Mechelen,2800,NaN,Mechelen/Walem,10507,NaN,NaN,Duivenstraat,BE-VLG,current
2,114333.83,206615.16,51.168450,3.858826,205003,NaN,7,44073,NaN,NaN,Wachtebeke,9185,NaN,Wachtebeke,73796,NaN,NaN,Meersstraat,BE-VLG,current
3,101658.93,179174.69,50.920879,3.681247,205004,NaN,67,44020,NaN,NaN,Gavere,9890,NaN,Asper/Baaigem/Dikkelvenne/Gavere/Semmerzake/Vu...,69428,NaN,NaN,Nijverheidsstraat,BE-VLG,current
4,103887.16,195997.07,51.072272,3.710817,205005,NaN,1A,44021,Gent,Gand,Gent,9000,NaN,Gent,70689,NaN,NaN,Klaverstraat,BE-VLG,current

In [9]:
df_flandre.isna().sum()

EPSG:31370_x                  0
EPSG:31370_y                  0
EPSG:4326_lat                 0
EPSG:4326_lon                 0
address_id                    0
box_number              2866095
house_number                  0
municipality_id               0
municipality_name_de    2621741
municipality_name_fr    2567839
municipality_name_nl          0
postcode                      0
postname_fr             3848550
postname_nl                   0
street_id                     0
streetname_de           3875323
streetname_fr           3821681
streetname_nl                 0
region_code                   0
status                        0
dtype: int64

In [10]:
df_flandre['postcode'] = df_flandre['postcode'].astype('str')

In [12]:
df_flandre["Address"] = df_flandre["streetname_nl"] + " " + df_flandre["house_number"] + " " +\  
                        df_flandre['postcode'] + " " +  df_flandre['municipality_name_nl']

In [13]:
df_flandre_address =  df_flandre[['Address', 'EPSG:31370_x','EPSG:31370_y',
                                  'EPSG:4326_lat','EPSG:4326_lon','region_code']]

In [14]:
df_flandre_address.drop_duplicates(subset='Address', keep="first", inplace=True)

<ipython-input-14-1056a3b00642>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_flandre_address.drop_duplicates(subset='Address', keep="first", inplace=True)

In [15]:
df_flandre_address.reset_index(drop=True,inplace=True)

In [16]:
df_flandre_address

,Address,EPSG:31370_x,EPSG:31370_y,EPSG:4326_lat,EPSG:4326_lon,region_code
0,Steenweg op Oosthoven 51 2300 Turnhout,190710.56,224659.47,51.330293,4.952837,BE-VLG
1,Duivenstraat 102 2800 Mechelen,158832.72,192858.98,51.045829,4.494707,BE-VLG
2,Meersstraat 7 9185 Wachtebeke,114333.83,206615.16,51.168450,3.858826,BE-VLG
3,Nijverheidsstraat 67 9890 Gavere,101658.93,179174.69,50.920879,3.681247,BE-VLG
4,Klaverstraat 1A 9000 Gent,103887.16,195997.07,51.072272,3.710817,BE-VLG
...,...,...,...,...,...,...
2823778,Zavelputten 20 9620 Zottegem,112288.80,173852.84,50.873827,3.832964,BE-VLG
2823779,Elenestraat 224 9620 Zottegem,110688.57,175738.80,50.890674,3.810028,BE-VLG
2823780,Elenestraat 226 9620 Zottegem,110687.08,175747.24,50.890750,3.810006,BE-VLG
2823781,Kernemelkstraat 23A 9620 Zottegem,107542.27,177059.58,50.902325,3.765160,BE-VLG
2823782,Eénmeilaan 13 3010 Leuven,174646.92,175159.43,50.886268,4.719019,BE-VLG

## Brussels Addresses

In [17]:
df_bru.head()

,EPSG:31370_x,EPSG:31370_y,EPSG:4326_lat,EPSG:4326_lon,address_id,box_number,house_number,municipality_id,municipality_name_de,municipality_name_fr,municipality_name_nl,postcode,postname_fr,postname_nl,street_id,streetname_de,streetname_fr,streetname_nl,region_code,status
0,148083.0,173673.0,50.873427,4.341517,1433854,NaN,209,21004,NaN,Bruxelles,Brussel,1020,Bruxelles (Laeken),Brussel (Laken),37080,NaN,Avenue Richard Neybergh,Richard Neyberghlaan,BE-BRU,current
1,148334.0,167104.0,50.814376,4.345112,1511655,NaN,28,21007,NaN,Forest,Vorst,1190,Forest,Vorst,39352,NaN,Rue de la Mutualité,Onderlinge Bijstandstraat,BE-BRU,current
2,151886.0,173336.0,50.870397,4.395546,1407345,NaN,275,21006,NaN,Evere,Evere,1140,Evere,Evere,36502,NaN,Rue du Tilleul,Lindestraat,BE-BRU,current
3,146243.0,173684.0,50.873517,4.315375,1589937,NaN,17,21008,NaN,Ganshoren,Ganshoren,1083,Ganshoren,Ganshoren,41286,NaN,Rue Jean De Greef,Jean De Greefstraat,BE-BRU,current
4,152349.0,166257.0,50.806759,4.402077,1466088,NaN,8,21017,NaN,Watermael-Boitsfort,Watermaal-Bosvoorde,1170,Watermael-Boitsfort,Watermaal-Bosvoorde,38394,NaN,Rue du Bien-Faire,Bien-Fairestraat,BE-BRU,current

In [18]:
df_bru.isna().sum()

EPSG:31370_x                 0
EPSG:31370_y                 0
EPSG:4326_lat                0
EPSG:4326_lon                0
address_id                   0
box_number              221416
house_number                 0
municipality_id              0
municipality_name_de    549802
municipality_name_fr         0
municipality_name_nl         0
postcode                     0
postname_fr                  0
postname_nl                  0
street_id                    0
streetname_de           549802
streetname_fr                0
streetname_nl                0
region_code                  0
status                       0
dtype: int64

In [19]:
df_bru['postcode'] = df_bru['postcode'].astype('str')

In [21]:
df_bru["Address"] = df_bru["streetname_fr"] + " " + df_bru["house_number"] + " " +\
                     df_bru['postcode'] + " " +  df_bru['municipality_name_fr']

In [22]:
df_bru_address =  df_bru[['Address','EPSG:31370_x','EPSG:31370_y',
                         'EPSG:4326_lat','EPSG:4326_lon','region_code']]

In [23]:
df_bru_address.drop_duplicates(subset='Address', keep="first", inplace=True)

<ipython-input-23-56ec67776afa>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bru_address.drop_duplicates(subset='Address', keep="first", inplace=True)

In [24]:
df_bru_address.reset_index(drop=True,inplace=True)

In [25]:
df_bru_address

,Address,EPSG:31370_x,EPSG:31370_y,EPSG:4326_lat,EPSG:4326_lon,region_code
0,Avenue Richard Neybergh 209 1020 Bruxelles,148083.0,173673.0,50.873427,4.341517,BE-BRU
1,Rue de la Mutualité 28 1190 Forest,148334.0,167104.0,50.814376,4.345112,BE-BRU
2,Rue du Tilleul 275 1140 Evere,151886.0,173336.0,50.870397,4.395546,BE-BRU
3,Rue Jean De Greef 17 1083 Ganshoren,146243.0,173684.0,50.873517,4.315375,BE-BRU
4,Rue du Bien-Faire 8 1170 Watermael-Boitsfort,152349.0,166257.0,50.806759,4.402077,BE-BRU
...,...,...,...,...,...,...
221438,Rue de Genève 506 1030 Schaerbeek,152551.0,172117.0,50.859437,4.404984,BE-BRU
221439,Avenue Albert Desenfans 13 1030 Schaerbeek,151079.0,173352.0,50.870543,4.384081,BE-BRU
221440,Avenue Ernest Renan 35 1030 Schaerbeek,150981.0,172990.0,50.867289,4.382688,BE-BRU
221441,Avenue Ernest Renan 33 1030 Schaerbeek,150961.0,172988.0,50.867271,4.382404,BE-BRU
221442,Rue Godefroid Guffens 39 1030 Schaerbeek,151722.0,172928.0,50.866730,4.393214,BE-BRU

## Wallonie Addresses

In [26]:
df_wal.head()

,EPSG:31370_x,EPSG:31370_y,EPSG:4326_lat,EPSG:4326_lon,address_id,box_number,house_number,municipality_id,municipality_name_de,municipality_name_fr,municipality_name_nl,postcode,postname_fr,postname_nl,street_id,streetname_de,streetname_fr,streetname_nl,region_code,status
0,150915.6320,152830.7620,50.686064,4.381707,1522363,B001,93,25014,NaN,Braine-l'Alleud,NaN,1420,NaN,NaN,7700328,NaN,Chaussée Reine Astrid,NaN,BE-WAL,current
1,150915.6320,152830.7620,50.686064,4.381707,1522364,C003,93,25014,NaN,Braine-l'Alleud,NaN,1420,NaN,NaN,7700328,NaN,Chaussée Reine Astrid,NaN,BE-WAL,current
2,151281.9948,152320.9902,50.681481,4.386889,1522367,D004,103,25014,NaN,Braine-l'Alleud,NaN,1420,NaN,NaN,7700317,NaN,Boulevard de l'Europe,NaN,BE-WAL,current
3,150994.1490,152550.0550,50.683541,4.382817,1522368,0001,17,25014,NaN,Braine-l'Alleud,NaN,1420,NaN,NaN,7700317,NaN,Boulevard de l'Europe,NaN,BE-WAL,current
4,150994.1490,152550.0550,50.683541,4.382817,1522371,C003,17,25014,NaN,Braine-l'Alleud,NaN,1420,NaN,NaN,7700317,NaN,Boulevard de l'Europe,NaN,BE-WAL,current

In [27]:
df_wal.isna().sum()

EPSG:31370_x                  0
EPSG:31370_y                  0
EPSG:4326_lat                 0
EPSG:4326_lon                 0
address_id                    0
box_number              1522143
house_number                  0
municipality_id               0
municipality_name_de    1848335
municipality_name_fr      43209
municipality_name_nl    1891544
postcode                      0
postname_fr             1891544
postname_nl             1891544
street_id                     0
streetname_de           1848335
streetname_fr             43209
streetname_nl           1891544
region_code                   0
status                        0
dtype: int64

In [28]:
df_wal['postcode'] = df_wal['postcode'].astype('str')

In [30]:
df_wal["Address"] = df_wal["streetname_fr"] + " " + df_wal["house_number"] + " " +\
                    df_wal['postcode'] + " " +  df_wal['municipality_name_fr']

In [31]:
df_wal_address =  df_wal[['Address','EPSG:31370_x','EPSG:31370_y',
                          'EPSG:4326_lat','EPSG:4326_lon','region_code']]

In [32]:
df_wal_address.drop_duplicates(subset='Address', keep="first",inplace=True)

<ipython-input-32-750802287a84>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_wal_address.drop_duplicates(subset='Address', keep="first",inplace=True)

In [33]:
df_wal_address.reset_index(drop=True,inplace=True)

In [35]:
df_wal_address

,Address,EPSG:31370_x,EPSG:31370_y,EPSG:4326_lat,EPSG:4326_lon,region_code
0,Chaussée Reine Astrid 93 1420 Braine-l'Alleud,150915.6320,152830.7620,50.686064,4.381707,BE-WAL
1,Boulevard de l'Europe 103 1420 Braine-l'Alleud,151281.9948,152320.9902,50.681481,4.386889,BE-WAL
2,Boulevard de l'Europe 17 1420 Braine-l'Alleud,150994.1490,152550.0550,50.683541,4.382817,BE-WAL
3,Boulevard de l'Europe 19 1420 Braine-l'Alleud,151009.7500,152545.2140,50.683497,4.383038,BE-WAL
4,Boulevard de l'Europe 26 1420 Braine-l'Alleud,150949.4630,152500.9000,50.683099,4.382185,BE-WAL
...,...,...,...,...,...,...
1488525,Rue Baille de Fer 10 7370 Dour,0.0000,0.0000,49.293335,2.306689,BE-WAL
1488526,Rue Kangourou 8 5542 Hastière,183779.8140,98997.4730,50.201119,4.841900,BE-WAL
1488527,Rue du Ventilateur 18B 4000 Liège,233728.8830,150144.3080,50.655905,5.552888,BE-WAL
1488528,Place de Strépy 31 7110 La Louvière,0.0000,0.0000,49.293335,2.306689,BE-WAL
1488529,Parc Résidentiel Le Bosquet 68 6440 Froidchapelle,146544.2749,95381.9245,50.169574,4.320370,BE-WAL

In [36]:
filt = (df_wal_address['EPSG:31370_x'] != 0.0000) | (df_wal_address['EPSG:31370_y'] != 0.0000)

In [37]:
df_wal_address = df_wal_address[filt]

In [38]:
df_wal_address.reset_index(drop=True,inplace=True)

In [39]:
df_wal_address

,Address,EPSG:31370_x,EPSG:31370_y,EPSG:4326_lat,EPSG:4326_lon,region_code
0,Chaussée Reine Astrid 93 1420 Braine-l'Alleud,150915.6320,152830.7620,50.686064,4.381707,BE-WAL
1,Boulevard de l'Europe 103 1420 Braine-l'Alleud,151281.9948,152320.9902,50.681481,4.386889,BE-WAL
2,Boulevard de l'Europe 17 1420 Braine-l'Alleud,150994.1490,152550.0550,50.683541,4.382817,BE-WAL
3,Boulevard de l'Europe 19 1420 Braine-l'Alleud,151009.7500,152545.2140,50.683497,4.383038,BE-WAL
4,Boulevard de l'Europe 26 1420 Braine-l'Alleud,150949.4630,152500.9000,50.683099,4.382185,BE-WAL
...,...,...,...,...,...,...
1350700,Rue Joseph Gélis 21 4820 Dison,254187.3277,145162.8312,50.607838,5.840757,BE-WAL
1350701,Rue du Baty 16 5070 Fosses-la-Ville,173979.4150,118296.6280,50.375107,4.705857,BE-WAL
1350702,Rue Kangourou 8 5542 Hastière,183779.8140,98997.4730,50.201119,4.841900,BE-WAL
1350703,Rue du Ventilateur 18B 4000 Liège,233728.8830,150144.3080,50.655905,5.552888,BE-WAL
1350704,Parc Résidentiel Le Bosquet 68 6440 Froidchapelle,146544.2749,95381.9245,50.169574,4.320370,BE-WAL

## Combine addressess

In [40]:
df_address = pd.concat([df_flandre_address , df_bru_address , df_wal_address],ignore_index=True)
df_address

,Address,EPSG:31370_x,EPSG:31370_y,EPSG:4326_lat,EPSG:4326_lon,region_code
0,Steenweg op Oosthoven 51 2300 Turnhout,190710.5600,224659.4700,51.330293,4.952837,BE-VLG
1,Duivenstraat 102 2800 Mechelen,158832.7200,192858.9800,51.045829,4.494707,BE-VLG
2,Meersstraat 7 9185 Wachtebeke,114333.8300,206615.1600,51.168450,3.858826,BE-VLG
3,Nijverheidsstraat 67 9890 Gavere,101658.9300,179174.6900,50.920879,3.681247,BE-VLG
4,Klaverstraat 1A 9000 Gent,103887.1600,195997.0700,51.072272,3.710817,BE-VLG
...,...,...,...,...,...,...
4395926,Rue Joseph Gélis 21 4820 Dison,254187.3277,145162.8312,50.607838,5.840757,BE-WAL
4395927,Rue du Baty 16 5070 Fosses-la-Ville,173979.4150,118296.6280,50.375107,4.705857,BE-WAL
4395928,Rue Kangourou 8 5542 Hastière,183779.8140,98997.4730,50.201119,4.841900,BE-WAL
4395929,Rue du Ventilateur 18B 4000 Liège,233728.8830,150144.3080,50.655905,5.552888,BE-WAL
4395930,Parc Résidentiel Le Bosquet 68 6440 Froidchapelle,146544.2749,95381.9245,50.169574,4.320370,BE-WAL

In [41]:
df_address['Address'].nunique()

4395930

In [50]:
df_address.describe(include='all')

,Address,EPSG:31370_x,EPSG:31370_y,EPSG:4326_lat,EPSG:4326_lon,region_code
count,4395930,4.395931e+06,4.395931e+06,4.395931e+06,4.395931e+06,4395931
unique,4395930,NaN,NaN,NaN,NaN,3
top,Avenue de Guéménée 48 1420 Braine-l'Alleud,NaN,NaN,NaN,NaN,BE-VLG
freq,1,NaN,NaN,NaN,NaN,2823783
mean,NaN,1.518285e+05,1.718596e+05,5.085455e+01,4.393301e+00,NaN
std,NaN,5.462458e+04,3.543474e+04,3.188121e-01,7.752926e-01,NaN
min,NaN,2.289128e+04,2.174777e+04,4.950215e+01,2.554829e+00,NaN
25%,NaN,1.120412e+05,1.502404e+05,5.065837e+01,3.830741e+00,NaN
50%,NaN,1.519970e+05,1.763058e+05,5.089450e+01,4.397155e+00,NaN
75%,NaN,1.895554e+05,1.983343e+05,5.109258e+01,4.931484e+00,NaN
max,NaN,2.820974e+05,2.439890e+05,5.150477e+01,6.233429e+00,NaN

In [44]:
df_address.to_csv('/Users/adamtky/Desktop/BeCode/3. Project/Project 3 - 3D Houses/Data/Belgium_Address.csv')

## Example of searching an address

In [45]:
address = 'Klaverstraat 1A 9000 Gent'

In [46]:
index = []

for i in range(df_address.shape[0]):

    if df_address['Address'][i] == address :
        index.append(i)
        break
    continue

In [47]:
index

[4]

In [48]:
df_address['EPSG:31370_x'][index][index[0]] ,df_address['EPSG:31370_y'][index][index[0]]

(103887.16, 195997.07)

In [49]:
df_address['EPSG:4326_lat'][index][index[0]] ,df_address['EPSG:4326_lon'][index][index[0]]

(51.072272151424244, 3.710817495853669)